### PR TITLE
Fix link with jansson

### PR DESCRIPTION
**Pull request by orgads**
```
jansson/lib/libjansson.a(value.o): In function `json_real':
value.c:(.text+0x3134): undefined reference to `__isnan'
value.c:(.text+0x314c): undefined reference to `__isinf'
jansson/lib/libjansson.a(value.o): In function `json_real_set':
value.c:(.text+0x3294): undefined reference to `__isnan'
value.c:(.text+0x32ac): undefined reference to `__isinf'
collect2: error: ld returned 1 exit status
```

### CODE REVIEW

**Comment by JoshMcCullough** [comment]
@fitzyjoe can you review this, please?

**Comment by JoshMcCullough** [comment]
@orgads thanks for the PR! Can you explain what `-lm` does for us here?

**Comment by orgads** [comment]
Links with the standard math lib. I don't remember what function was used from there.

**Comment by JoshMcCullough** [comment]
This looks good, just needs to be rebased.

**Pull request merged**
