### PR TITLE
Use a bash function for tests

### PR DESCRIPTION
**Pull request by maxx-t**
Hi there, I just did some style modifications:
 - factorized tests a bit using a bash function 
 - split the build.sh file (added a test.sh one)
 - added a .gitignore to avoid to commit the .so file

### CODE REVIEW

**Comment by kevinmichaelchen** [comment]
[You should use `local` when setting variables](https://github.com/progrium/bashstyle)

**Comment by kevinmichaelchen** [comment]
Other than that we super appreciate the contribution. I'll let @fitzyjoe review this

**Comment by fitzyjoe** [comment]
Thanks @maxx-t, I like that you've separated the build from the test.  Unfortunately, the tests fail for me because I'm on a mac and it's using "localhost".  I'm not sure I understand the "if" for OSTYPE - none of this bash script is going to work for Windows, right?  On my mac, this is what works for me.  In which environment does this not work?

```
MACHINE_IP=`docker-machine ip 2> /dev/null`
```

Can we just use that line instead of the OSTYPE if block?

**Comment by maxx-t** [comment]
Of course, that's my bad, I thought that docker machine was a kind of "docker for windows".
I usually use the `docker` command on macOS too.

`"$OSTYPE" == "darwin"*` matches any macOS version (like `darwin15.6.0`) while `"$OSTYPE" == "linux"*` matches any linux (like `linux-gnu`).

I will reset this block to the original one.

**Pull request merged**
